// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "guyuxiang",
            "url": "https://guyuxiang.github.io",
            "email": "gu_yuxiang@qq.com"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/inner/chain-data-subscribe/solana/address-subscribe": {
            "post": {
                "description": "Register an address subscription to watch transactions related to a wallet address.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Solana"
                ],
                "summary": "Subscribe address activity",
                "parameters": [
                    {
                        "description": "Address subscription request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.AddressSubscribeRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/inner/chain-data-subscribe/solana/address-subscribe-cancel": {
            "post": {
                "description": "Cancel an existing address subscription by wallet address.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Solana"
                ],
                "summary": "Cancel address subscription",
                "parameters": [
                    {
                        "description": "Address subscription cancel request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.AddressSubscribeCancelRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/inner/chain-data-subscribe/solana/tx-subscribe": {
            "post": {
                "description": "Register a transaction subscription to watch a transaction until the configured end block.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Solana"
                ],
                "summary": "Subscribe transaction updates",
                "parameters": [
                    {
                        "description": "Transaction subscription request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.TxSubscribeRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/inner/chain-data-subscribe/solana/tx-subscribe-cancel": {
            "post": {
                "description": "Cancel an existing transaction subscription by transaction code.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Solana"
                ],
                "summary": "Cancel transaction subscription",
                "parameters": [
                    {
                        "description": "Transaction subscription cancel request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.TxSubscribeCancelRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/inner/chain-data/solana/common/address-balance": {
            "post": {
                "description": "Get the native SOL balance of a wallet address on the configured Solana network.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Solana"
                ],
                "summary": "Query native balance by address",
                "parameters": [
                    {
                        "description": "Address balance request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.AddressBalanceRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/inner/chain-data/solana/common/latest-block": {
            "post": {
                "description": "Get the latest observed Solana block number and timestamp.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Solana"
                ],
                "summary": "Query latest block",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/inner/chain-data/solana/common/token-add": {
            "post": {
                "description": "Add a token definition into database-backed token registry.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Solana"
                ],
                "summary": "Add or update token",
                "parameters": [
                    {
                        "description": "Token add request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.TokenAddRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/inner/chain-data/solana/common/token-balance": {
            "post": {
                "description": "Get the balance of a configured SPL token for a specific wallet address.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Solana"
                ],
                "summary": "Query token balance",
                "parameters": [
                    {
                        "description": "Token balance request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.TokenBalanceRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/inner/chain-data/solana/common/token-delete": {
            "post": {
                "description": "Delete a token definition from database-backed token registry by token code.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Solana"
                ],
                "summary": "Delete token",
                "parameters": [
                    {
                        "description": "Token delete request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.TokenDeleteRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/inner/chain-data/solana/common/token-get": {
            "post": {
                "description": "Get a token definition from database-backed token registry by token code.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Solana"
                ],
                "summary": "Get token",
                "parameters": [
                    {
                        "description": "Token get request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.TokenGetRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/inner/chain-data/solana/common/token-list": {
            "post": {
                "description": "List token definitions from database-backed token registry, optionally filtered by network code.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Solana"
                ],
                "summary": "List tokens",
                "parameters": [
                    {
                        "description": "Token list request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.TokenListRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/inner/chain-data/solana/common/token-supply": {
            "post": {
                "description": "Get the total supply of a configured SPL token by token code.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Solana"
                ],
                "summary": "Query token supply",
                "parameters": [
                    {
                        "description": "Token supply request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.TokenSupplyRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/inner/chain-data/solana/common/tx-query": {
            "post": {
                "description": "Query on-chain transaction status, summary data, and decoded events by transaction code.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Solana"
                ],
                "summary": "Query a transaction",
                "parameters": [
                    {
                        "description": "Transaction query request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.TxQueryRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/inner/chain-invoke/solana/common/tx-send": {
            "post": {
                "description": "Broadcast a signed transaction and automatically create a transaction subscription window.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Solana"
                ],
                "summary": "Send a signed Solana transaction",
                "parameters": [
                    {
                        "description": "Signed transaction payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.TxSendRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/inner/chain-invoke/solana/wallet/faucet": {
            "post": {
                "description": "Send native SOL from the configured faucet account to the target address and automatically subscribe the transaction.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Solana"
                ],
                "summary": "Send faucet tokens",
                "parameters": [
                    {
                        "description": "Faucet request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.FaucetRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.AddressBalanceRequest": {
            "type": "object",
            "required": [
                "address"
            ],
            "properties": {
                "address": {
                    "type": "string"
                }
            }
        },
        "models.AddressSubscribeCancelRequest": {
            "type": "object",
            "required": [
                "address"
            ],
            "properties": {
                "address": {
                    "type": "string"
                }
            }
        },
        "models.AddressSubscribeRequest": {
            "type": "object",
            "required": [
                "address"
            ],
            "properties": {
                "address": {
                    "type": "string"
                }
            }
        },
        "models.ErrorResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "models.FaucetRequest": {
            "type": "object",
            "required": [
                "acceptAddress",
                "idempotencyKey",
                "value"
            ],
            "properties": {
                "acceptAddress": {
                    "type": "string"
                },
                "idempotencyKey": {
                    "type": "string"
                },
                "value": {
                    "type": "number"
                }
            }
        },
        "models.Response": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "data": {},
                "message": {
                    "type": "string"
                }
            }
        },
        "models.SubscribeRange": {
            "type": "object",
            "properties": {
                "endBlockNumber": {
                    "type": "integer"
                },
                "startBlockNumber": {
                    "type": "integer"
                }
            }
        },
        "models.TokenAddRequest": {
            "type": "object",
            "required": [
                "code",
                "decimals",
                "mintAddress",
                "networkCode"
            ],
            "properties": {
                "code": {
                    "type": "string"
                },
                "decimals": {
                    "type": "integer"
                },
                "mintAddress": {
                    "type": "string"
                },
                "networkCode": {
                    "type": "string"
                }
            }
        },
        "models.TokenBalanceRequest": {
            "type": "object",
            "required": [
                "address",
                "tokenCode"
            ],
            "properties": {
                "address": {
                    "type": "string"
                },
                "tokenCode": {
                    "type": "string"
                }
            }
        },
        "models.TokenDeleteRequest": {
            "type": "object",
            "required": [
                "code"
            ],
            "properties": {
                "code": {
                    "type": "string"
                }
            }
        },
        "models.TokenGetRequest": {
            "type": "object",
            "required": [
                "code"
            ],
            "properties": {
                "code": {
                    "type": "string"
                }
            }
        },
        "models.TokenListRequest": {
            "type": "object",
            "properties": {
                "networkCode": {
                    "type": "string"
                }
            }
        },
        "models.TokenSupplyRequest": {
            "type": "object",
            "required": [
                "tokenCode"
            ],
            "properties": {
                "tokenCode": {
                    "type": "string"
                }
            }
        },
        "models.TxQueryRequest": {
            "type": "object",
            "required": [
                "txCode"
            ],
            "properties": {
                "txCode": {
                    "type": "string"
                }
            }
        },
        "models.TxSendRequest": {
            "type": "object",
            "required": [
                "txSignResult"
            ],
            "properties": {
                "txSignResult": {
                    "type": "string"
                }
            }
        },
        "models.TxSubscribeCancelRequest": {
            "type": "object",
            "required": [
                "txCode"
            ],
            "properties": {
                "txCode": {
                    "type": "string"
                }
            }
        },
        "models.TxSubscribeRequest": {
            "type": "object",
            "required": [
                "subscribeRange",
                "txCode"
            ],
            "properties": {
                "subscribeRange": {
                    "$ref": "#/definitions/models.SubscribeRange"
                },
                "txCode": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.1.0",
	Host:             "",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Swagger projectc-solana-connector",
	Description:      "This is a projectc-solana-connector.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
